name: kobybrann
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  image_picker:
  cupertino_icons: ^1.0.0
  # emojis
  emoji_picker: ^0.1.0
  flutter_keyboard_visibility: ^3.2.2


 # cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


